variables:
  - name: isRunningUsingAzureDevOpsCloud
    value: false 

stages:
- stage: deploy_to_test
  jobs:
    - job: deployToTest
      displayName: 'deploy to test'
      steps:
      - task: DownloadPipelineArtifact@2
        condition: eq(variables['isRunningUsingAzureDevOpsCloud'], true)
        inputs:
          buildType: 'current'
          artifactName: 'drop'
          targetPath: '$(System.ArtifactsDirectory)\drop'
